version: '3.8'

networks:
  web:
    external: true

services:
  kp-web-app:
    build: .
    image: kp-web-app
    container_name: web-app-container
    restart: unless-stopped
    labels:
      - "traefik.backend=kp-web-app"
      - "traefik.frontend.rule=Host:wbgkp.quanti.ca"
      - "traefik.docker.network=web"
      - "traefik.port=80"
      - "traefik.frontend.entryPoints=http,https"
    networks:
      - web
