version: '3.8'

networks:
  web:
    external: true

services:
  kp-web-app:
    build: .
    image: kp-web-app
    container_name: web-app-container
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kp-web-app.rule=Host(`wbgkp.quanti.ca`)"
      - "traefik.http.routers.kp-web-app.entrypoints=web"
      - "traefik.http.services.kp-web-app.loadbalancer.server.port=80"
      - "traefik.docker.network=web"
    networks:
      - web
